package sample.data.elasticsearch;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import sample.data.elasticsearch.model.Person;
import sample.data.elasticsearch.repository.PersonRepository;
import sample.data.elasticsearch.service.PersonInjectorService;

@SpringBootApplication
public class PeopleSearchApplication implements CommandLineRunner {

    @Autowired
    private PersonRepository personRepository;

    @Autowired
    private PersonInjectorService personInjectorService;

    @Override
    public void run(String... args) throws Exception {
        personRepository.deleteAll();
        personInjectorService.generateAndSaveVideos(50);
        searchPeople();
    }

    private void searchPeople() {
        System.out.println("Total elements on the index :");
        System.out.println("-------------------------------");
        long totalCount = personRepository.count();
        System.out.println(totalCount);

        Person person = personRepository.findByName("Name 46");
        System.out.println("Person found through the autogenerated elastic search repository :");
        System.out.println("-------------------------------");
        System.out.println(person);

        System.out.println();
    }

    public static void main(String[] args) throws Exception {
        SpringApplication.run(PeopleSearchApplication.class, args);
    }

}
